### ISSUE TITLE
Question about equation 22 in the original paper

### ISSUE THREAD

**Issue by yusuke0519** [yasu0001/multicoated-supermasks#1]
Hi, thank you for sharing very brilliant works. 

I have read your paper, but could not fully understand how we should set k. 

According to the paper (equation 22), you mentioned that the i-th remain rate should be $k_i = k_1*i/N$.
However, it gives higher remain rate for the later remain rate, e.g., if N=3 and k_1 = 0.1, k_1 = 0.33, k_2 = 0.67 and k_3 = 0.1. 

Is it correct? or is is actually $k_i = k_1*(N+1-i)/N$? 

Thanks, in advance.

**Comment by yasu0001** [comment]
@yusuke0519 

Thank you for your comments and we'd appreciate your interest on our search. We have carefully examined our paper based on your question and identified two errors in Equation (21) and Equation (23). The corrected equations are as follows:
Equation(21):
$s_{t_n} = s_{t_{1}} + (\alpha - s_{t_1})\frac{n-1}{N},$

and Equation(23):
$k_n = k_1 \frac{N+1-n}{N}.$

We appreciate your time and consideration in providing feedback. If you have any further comments or questions, please feel free to let us know.

**Comment by yusuke0519** [comment]
@yasu0001 Thank you for your prompt reply!  It really helped me.
